# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-01 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='feed_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
